# Generated by Django 4.0.1 on 2022-12-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='banner',
            field=models.ImageField(upload_to='shop/images'),
        ),
    ]
