# Generated by Django 4.0.1 on 2022-12-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0004_alter_members_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='banner',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
