# Generated by Django 4.0.1 on 2022-12-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0005_alter_members_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('feed', models.CharField(max_length=25)),
            ],
        ),
    ]
